### ISSUE TITLE
UUIDize the SQL backend?

### ISSUE THREAD

**Issue by macieksmuga** [BD2KGenomics/hgvm#10]

**Comment by macieksmuga** [comment]
After a vigorous debate between Mark and Jerome, I'm not sure we're quite ready for this yet: I can get along with using (local) numerical ID's for sequences, and (unique within a reference set) names for reference sequences.

**Comment by diekhans** [comment]
Do we know what the immutable boundaries for hgvm?

**Comment by macieksmuga** [comment]
Decided to defer this for now. Argument about primary key sizes is valid, may interfere with scalability.
