### ISSUE TITLE
GETting bases from server is slow!

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/hgvm#115]
Since we have 1 sequence / SNP, even our small test servers can have tens of thousands of sequences.  Sending a GET request for each one is slow, and not practical for even the SMA region (5 seconds to download fasta directly,  9 minutes to run the 1995 GETs). At that rate it would take hours just to download the MHC region.

**Comment by glennhickey** [comment]
New interface to get bases in the POST request for sequences helps quite a bit.  But still at point where downloading sequences for camel-mhc (FASTA=11MB) is taking close to an hour.

**Comment by macieksmuga** [comment]
@glennhickey Please re-test, now that I eliminated a major bug in the server that caused serious latency problems for queries with high pageToken values. Independently, I'm going to implement one further (pre-processing) optimization over the next day or two that will hopefully result in a much speedier serving out of bases.

**Comment by macieksmuga** [comment]
Should be resolved with this PR: https://github.com/ga4gh/server/pull/556
