### ISSUE TITLE
make pilot region graphs from simons VCF files

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/hgvm#131]
In the same way as we used the 1000-genomes vcfs,  we can construct pilot region graphs using the simons dataset. The VCF file will be here:

/hive/users/benedict/simons (it's downloading right now)

I presume this means extracting the region from the VCF then running it through VG.

**Comment by glennhickey** [comment]
Just to confirm, this is on grc38?

**Comment by benedictpaten** [comment]
Ooh, good question. Standby, I will confirm/deny.
