### ISSUE TITLE
Make Simons and 1000 Genomes graph servers

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/hgvm#132]
Data is here:

Simons:

/hive/users/hickey/ga4gh/simons/MHC
/hive/users/hickey/ga4gh/simons/SMA
/hive/users/hickey/ga4gh/simons/LRC_KIR

1000 Genomes GRC38 SNPS:

/hive/users/hickey/ga4gh/vg/bakeoff/MHC
/hive/users/hickey/ga4gh/vg/bakeoff/SMA
/hive/users/hickey/ga4gh/vg/bakeoff/LRC_KIR

thanks

**Comment by glennhickey** [comment]
@macieksmuga, I added BRCA1 and BRCA2 graphs for both the Simons and 1kgp datasets mentioned below, if you could please throw those up as well... thanks!

**Comment by macieksmuga** [comment]
Importing them now, thanks @glennhickey!

**Comment by glennhickey** [comment]
Hi Maciek,

Thanks!  I just found out a second ago that I used the wrong genome (grc38)
for these.  Am regenerating now with grc37 (paths will be the same) and
will let you know when that's done.

**Comment by macieksmuga** [comment]
Is this for the simons, the 1kg or both?

**Comment by glennhickey** [comment]
This is only for simons, which I just updated.  So we now have (all links
should work now):

1KG

/hive/users/hickey/ga4gh/vg/bakeoff/BRCA1
/hive/users/hickey/ga4gh/vg/bakeoff/BRCA2
/hive/users/hickey/ga4gh/vg/bakeoff/MHC
/hive/users/hickey/ga4gh/vg/bakeoff/SMA
/hive/users/hickey/ga4gh/vg/bakeoff/LRC_KIR

Simons GRCh37*:

/hive/users/hickey/ga4gh/simons/BRCA1
/hive/users/hickey/ga4gh/simons/BRCA2
/hive/users/hickey/ga4gh/simons/MHC
/hive/users/hickey/ga4gh/simons/SMA

That the Simons is on GRCh37 whereas all other submissions (I think) are on
38 is somewhat of a concern.  But I think most of the bakeoff statistics as
they stand will still be somewhat meaningful for now (but with an
asterisk).  I don't have LRC_KIR coordinates on GRCh37 at the moment, which
is why that one's missing..

thanks!
-Glenn

On Fri, Aug 21, 2015 at 1:03 PM, Maciek Smuga-Otto <notifications@github.com

**Comment by macieksmuga** [comment]
Simons graph servers are now up. Check the server list for their addresses.

**Comment by macieksmuga** [comment]
All requested servers are now added, annotated in the master server list.

**Comment by glennhickey** [comment]
Hi Maciek,

Mind taking down the Simons LRC_KIR graph for now?  It's an invalid graph
for GRCh38, whereas the others were corrected to GRCh37.  Sorry, this is my
bad for leaving the LRC_KIR softlink up (thought I'd erased it).

thanks!
-Glenn

On Fri, Aug 21, 2015 at 5:51 PM, Maciek Smuga-Otto <notifications@github.com
