### ISSUE TITLE
Tell Karen her l2 and l3 graphs are broken

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#142]

**Comment by glennhickey** [comment]
cenx-level2 http://ec2-54-149-188-244.us-west-2.compute.amazonaws.com/cenx-level2/:  Invalid input join: j(s(p(468,171),0),s(p(745,0),1)). Position of Side 1 (171) not within Sequence with ID=468 which has length=171

cenx-level3 http://ec2-54-149-188-244.us-west-2.compute.amazonaws.com/cenx-level3/:  Invalid input join: j(s(p(8,171),0),s(p(9,0),1)). Position of Side 1 (171) not within Sequence with ID=8 which has length=171

**Comment by macieksmuga** [comment]
Corresponded with Karen about this. CENX level 2 data suffered from a simple off-by-one error in one of its graph join constructions. The error in level 3 data is more subtle and not immediately amenable to a quick fix. Karen is working on it now.

**Comment by macieksmuga** [comment]
Level 2 CENX now passes the sg2vg test script:

```
(testenv)Maciejs-MacBook-Pro:sg2vg maciek$ python runOnServerList.py test.tsv ~/tmp/serverreport
sg2vg http://ec2-54-149-188-244.us-west-2.compute.amazonaws.com/cenx-level2/v0.6.g -u
Downloading References... (0 references retrieved)
Warning: No references found
Downloading Sequences... (2756 sequences retrieved)
Downloading Joins... (22203 joins retrieved)
Downloading allele paths... (0 paths retrieved)
Converting Side Graph to VG Sequence Graph
Writing VG JSON to stdout

0 Errors
```

**Comment by adamnovak** [comment]
OK, it's now on my list to test.

-Adam

On Fri, Aug 21, 2015 at 2:32 PM, Maciek Smuga-Otto <notifications@github.com

**Comment by macieksmuga** [comment]
I'll update this issue when I hear back from Karen about what's up with level 3.

**Comment by macieksmuga** [comment]
Karen promised a revised level 3 graph by Monday.

**Comment by macieksmuga** [comment]
Level 3 graph delivered, still some invalid index positions in the graphJoins. Emailed her with detailed bug report.
