### ISSUE TITLE
Get working graph from Jerome

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#143]

**Comment by glennhickey** [comment]
oxford-mhc  http://ec2-54-149-188-244.us-west-2.compute.amazonaws.com/oxford-mhc/:  Invalid input join: j(s(p(19,0),0),s(p(1,232489),1)). Position of Side 1 (0) not within Sequence with ID=19 which has length=0

**Comment by macieksmuga** [comment]
Update: Jerome has run into further problems generating a graph with no zero-length sequences. Promises an update early next week (around Monday Sept 8)
