### ISSUE TITLE
contact groups who have not yet submitted graphs

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/hgvm#150]
People to contact:
Erik Garrison
UTAH group
Seven Bridges

**Comment by macieksmuga** [comment]
I pinged Seven Bridges and the Utah group. We're already in ongoing discussions with Erik about his submission :)

**Comment by benedictpaten** [comment]
Good, thanks.

On Fri, Aug 28, 2015 at 8:50 AM, Maciek Smuga-Otto <notifications@github.com

**Comment by macieksmuga** [comment]
- Jerome (Oxford PRG): Having troubles generating graph - will have update around Monday Sept 8
- Seven Bridges: zip, zilch. I emailed them a couple of times already. Beginning to feel like a telemarketer.
- Utah: Emailed them once in the last week, will email again.

**Comment by benedictpaten** [comment]
Thanks for applying the pressure! I hope we can get these. Any update on
Erik's long read VG graphs?

Also, please insert a slide on this into the presentation (as the first
slide - showing the grid of regions and submitters, with ? for Seven
Bridges, Utah and Jerome.

On Tue, Sep 1, 2015 at 12:37 PM, Maciek Smuga-Otto <notifications@github.com
