### ISSUE TITLE
Collect high coverage FASTQ for getting the right reads

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#155]

**Comment by adamnovak** [comment]
@glennhickey: Do you need high coverage samples for variant calling? I think we decided to use the low coverage ones for the kmers and the mapping evaluation.

**Comment by glennhickey** [comment]
Having at least one high-coverage sample would be nice, as I'm not planning
on pooling samples together like (I think) 1000 genomes did... I don't
really have a sense of how big of an impact this will have on our metrics,
though.
