### ISSUE TITLE
use pinch graph code to create merged graphs for two input side graphs

### ISSUE THREAD

**Issue by benedictpaten** [BD2KGenomics/hgvm#174]
This is per discussion with David today.

**Comment by benedictpaten** [comment]
I am assigning this to you, Adam - because you are familiar with the code, but perhaps Glenn could take it on. I don't think it would take long.

**Comment by adamnovak** [comment]
String comparison: take SNPs and flanks from a variant database and see if you can find them in the graph. (This is a bit one-directional and the fully connected graph aces this test).

**Comment by adamnovak** [comment]
Common Core: collapse on a (covering) set of paths, and evaluate degree of collapse in the common core as a metric of graph-graph similarity.

**Comment by adamnovak** [comment]
I implemented a tool https://github.com/adamnovak/corg to make core graphs. Right now it just follows paths in the graph, but that's enough to do the "common core" for graphs built with the test data (that have paths implemented correctly).

Working on graphs without their own path info (or, like 1000g SNPs, built on a different reference) is going to require finding matching unique kmers, which will be a bit of a project. That probably deserves its own issue, so I'm closing this one.
