### ISSUE TITLE
Write methods and add charts to paper draft

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#186]

**Comment by adamnovak** [comment]
I have written up as much of my methods as I think is going to fit in any reasonable paper. There's still a need for an actual explanation of the crazy retraction and credit stuff I did for Camel for the supplement, and for maybe some more supplemental material detailing how to replicate the vg alignment runs.

I put in the figures I have, pending re-running on more than the 100 CEU people.

@srblum, @macieksmuga, and @glennhickey can add in all their methods too.

I'm going to call this a first draft of my stuff and close this issue. It's still riddled with TODOs, but that's what a second draft is for.

**Comment by glennhickey** [comment]
anyone else having problems opening the google doc?
