### ISSUE TITLE
Organize read simulation people

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#192]

**Comment by adamnovak** [comment]
Sean is writing a read simulator, but vg includes one that Erik is intent on upgrading, and Deniz has one and will be more available to help make it go after the graph submission deadline. I should get Sean to evaluate the different options and talk to the people and figure out which to use or finish his.

Features we want:
- Simulate reads with known side graph positions
- Add in sequencing-style errors: base substitutions and homopolymer indels
- Maybe generate qualities?
- Generate reads reflecting novel non-error variation not in the graph being aligned to: new SNPs and some indels. Be consistent on what genuine edits are generated within a given run of the simulator, so they can in theory be distinguished from sequencing errors.

**Comment by glennhickey** [comment]
"known side graph positions" is important but will have ramifications on
the rest of our pipeline, which does a good job of losing the side graph
coordinates, starting with sg2vg.  sg2vg can be modified to keep track of
the original coordinates (using paths as Adam suggested seems reasonable),
but is that enough?  vg isn't so great at preserving paths, it seems, so am
worried the coordinates would get lost in indexing, mapping, and/or variant
calling.
