### ISSUE TITLE
Point out the important graph read fields for the bake-off and their meanings and refs to sam spec

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#196]

**Comment by macieksmuga** [comment]
@adamnovak Each run of an algorithm that produces a read alignment will result in a new `ReadGroup` for that graph, right? The one piece of metadata that we'll absolutely need for each such will be:

```
  /** The programs used to generate this read group. */
  array<Program> programs = [];
```

where we standardize on how to describe the various candidate read alignment algorithms used. Not sure if any of the other fields will be useful for now, although I can certainly include them as nullable in a `ReadGroup` table.

We'll then have one containing `ReadGroupSet` for the artificial reads generated from the graph itself, perhaps another one or more for some real (sub)set of reads on that region from 1kg?

Within a `ReadAlignment` proper, we'll need the `readGroupId` to associate it with the program that ran it, and an `alignment` object. I'll admit to not really understanding if we need most of the SAM-derived flags, or what `Fragment` is doing for us there.

As for the `GraphAlignment` proper: The big compatibility-braking change to the SQL to support all this will be moving from an `Allele`-based path representation to a first-class `Path` table, with `Allele` only holding certain extra metadata. May not even end up being used in the graph server, period.

So yeah, apart from moving from `Allele` to `Path` and figuring out which SAM flags we need (oh, and the role of `Fragment`), it'll be, how you say, easy-peasy.

**Comment by adamnovak** [comment]
Sorry, I didn't see this; I already sent you a long e-mail.

`ReadGroup`s are defined by the sequencer, I think. You can end up with two or three `ReadGroup`s for a single sample. So basically all of what you describe here should move a level up. An alignment of a sample to a reference by an aligner is represented by a `ReadGroupSet`.

I don't think `programs` is really that important. We could annotate everything with the programs that did the alignment, but since we can't actually search by programs, we'll need to have different top-level `Dataset`s for the different aligners under test. Probably we will put them all on different server instances, like with the graphs, so you can just compare URLs against each other.
