### ISSUE TITLE
Swap over to text-based path output for aligner bake-off

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#215]

**Comment by adamnovak** [comment]
We won't need to do loads of reference server stuff, and apparently nobody liked the database thing from the last bake-off either.

**Comment by adamnovak** [comment]
OK I made a draft spec:

https://github.com/adamnovak/hgvm-aligner-bakeoff-compliance/blob/master/Text%20Alignment%20to%20Graph%20Format.md

**Comment by glennhickey** [comment]
Looks great, Adam!

Do you think there would be any push-back if we rid of the reverse flag
(0x10)?  As with deletions, this is information that can be specified in
the path.  From experience, it is much less confusing to only have one way
of representing this.

-Glenn

**Comment by adamnovak** [comment]
Actually, I talked to Maciek, and I'm now thinking of going a different
route, and basically just writing VG GAM files into a TSV with one
alignment per line. That would be a bit simpler, with less of a risk of
doing something subtly different than SAM. What do you think of that idea?
I'll write up a proper spec for it.

-Adam

**Comment by glennhickey** [comment]
Sounds like a fine idea to me.  My original point, removing the reverse
flag, still stands though!

**Comment by adamnovak** [comment]
Ok here's my attempt at a GAM-based format:

https://github.com/adamnovak/hgvm-aligner-bakeoff-compliance/blob/master/Text%20Graph%20Alignment%20Map%20Format.md

I'm keeping the orientation flag around, but I'm fixing the orientation in which you articulate the path (smaller node ID first), so I don't think there are two ways to spell everything.

This format has you repeating bits of the sequence in the path edits, like in the VG GAM format. It's a little repetitive, but it's probably easier to parse than CIGAR.

**Comment by glennhickey** [comment]
Looks good.  We should find a way to map this documentation onto the
original GAM format!!!

I'd add a little example for each of the four edit cases.  I think the
notation's dense enough that some people will get confused even though your
text is quite clear.

**Comment by adamnovak** [comment]
OK I added those examples, and I've circulated the TGAM format to the aligner bake-off participants. At the planning meeting today we decided to use that format because it's simpler and less confusingly close to SAM.
