### ISSUE TITLE
Figure out why mapped VG reads are giving terrible results

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#216]

**Comment by adamnovak** [comment]
Probably the lack of any real MAPQ algorithm is throwing off Glenn. But why is it putting nonsense MAPQ in the GAM files in the first place if it can't estimate it?

**Comment by glennhickey** [comment]
Yeah, I'm reading the "quality" bytes array from the Alignment messages.
They seem present in the GAMs.  For a quality byte q, I assume the
probability of an error at that base to be

pow(10., -(double)q / (10.));

This is the usual Phred score (without ascii correction as the protobuf
record doesn't seem to use it).  Checking some values by eye, they don't
seem totally insane.  Of course, if vg isn't computing qualities, then my
assumption above is still wrong.

(on a related note, a lot of my superfluous snps seem to be coming from not
using a high enough depth-threshold -- ie it'll call a snp even if only 5
reads align).

**Comment by adamnovak** [comment]
Those qualities are the sequencer base qualities. vg doesn't touch them, it
just copies them from the FASTQ file. They are for whether the base was
measured correctly, not whether that base agrees with the reference ir is
mapped correctly or anything.

I still don't think mapping qualities (i.e. SAM MAPQ, one per alignment)
are reported by vg.

-Adam

**Comment by glennhickey** [comment]
Right, thanks.  This is starting to ring a bell.  I'm using in the _read_
qualities (seemingly correctly) but ignoring _mapping_ qualities because vg
doesn't write them.  Never thought that doing this would have such an
effect.

**Comment by glennhickey** [comment]
I've found some major bugs in vg call that are likely at the root of much
of the problems (far more so that lack of mapping qualities, anyway).  The
new alignments seem to improve things (at first glance, anyway) too.
Optimistic that the next round of results will be semisensical. .

**Comment by adamnovak** [comment]
I'm going to assume that the results we presented at New York were sensical, and close this up. If there are more specific problems with VG read mapping, we can open another issue.

**Comment by glennhickey** [comment]
Agreed
