### ISSUE TITLE
Change vg edge limit to count only edges crossed

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#223]

**Comment by adamnovak** [comment]
Maybe as another option? It sort of makes it not useful on things like Curoverse

**Comment by adamnovak** [comment]
I thought Erik said that he has done this, but it doesn't look like he did in the code. I e-mailed him and I will see what he says.  Maybe someone misunderstood him and told me the wrong thing?

**Comment by glennhickey** [comment]
I'd understood the same thing (that Erik fixed this).  Believe Sean's the
one who spoke to Erik  at most length on this subject.

**Comment by adamnovak** [comment]
OK, I talked to Erik and convinced him that the way I want to do it (charge 0 when there are no alternatives and 1 when there are any alternatives) makes sense, so I'll go ahead and implement that.

**Comment by adamnovak** [comment]
This is now open (with a  bunch of other changes I needed in order to fix up vg's build on kolossus) as https://github.com/ekg/vg/pull/131.
