### ISSUE TITLE
Process new VG long reads graphs and stand up servers

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#247]

**Comment by macieksmuga** [comment]
@adamnovak Is there a brand-new version of VG long reads graphs out there to grab, or should I just re-run a fixed-up vg2sg on the same ones I have from a couple of weeks back?

**Comment by adamnovak** [comment]
I sent you a batch with whole-region graphs for all the regions, right? That's the ones that I had in mind. They are new compared to Erik's original graphs, for which we only had BRCA1 and BRCA2 in the right format.

**Comment by macieksmuga** [comment]
I just put them up here:
http://ec2-54-149-188-244.us-west-2.compute.amazonaws.com/vglr-brca2/
etc...
(except that brca1 still didn't work properly) 
- can you check out the rest to see if they look OK?

**Comment by adamnovak** [comment]
I think this has been done for a while.
