### ISSUE TITLE
Build VG long reads graphs again with support for cyclic paths

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#254]

**Comment by glennhickey** [comment]
Hi Adam,

Are you using a script to make these?  Do you mind sending it to me?
thanks
-Glenn

**Comment by adamnovak** [comment]
Hello,

I didn't make a file for my script, but I put it in my notes. It was:

wget http://hgwdev.sdsc.edu/~anovak/hgvm/hgvm.tar.gz
tar -xvzf hgvm.tar.gz
for REGION in `ls hgvm`
do
    # Set up a vg command
    VG_COMMAND=(vg msga -k 32 -m 32 -B 640 -D -f "hgvm/${REGION}/ref.fa")

```
for FASTA in `ls hgvm/${REGION} | grep -v ref.fa | grep '\.fa$'`
do
    # Add in all the non-ref FASTAs
    VG_COMMAND=(${VG_COMMAND[@]} "-f" "hgvm/${REGION}/${FASTA}")
done

echo ${VG_COMMAND[@]} ">${REGION}.vg"
```

done

I'm not actually sure that ordering it like this forces it to start with
ref. I may address that when I re-run it.

-Adam

**Comment by glennhickey** [comment]
Cool thanks, seems to run

**Comment by adamnovak** [comment]
I'm going to assume that you did this for me and close this.
