### ISSUE TITLE
Download all the high coverage samples for Glenn

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#256]

**Comment by adamnovak** [comment]
I have downloaded these samples and am running the alignments.

The reads are in /cluster/home/anovak/hive/ga4gh/bake-off/hgvm-graph-bakeoff-evalutations/high_coverage_reads and the alignments should show up in /cluster/home/anovak/hive/ga4gh/bake-off/hgvm-graph-bakeoff-evalutations/high_coverage_alignments (along with their zipped-up indexed graphs).

**Comment by glennhickey** [comment]
Thanks!

I'll quit downloading them myself now!

**Comment by glennhickey** [comment]
Hi Adam,

Is this still running?  Seems like only a couple graphs made it through
back on Nov 10...

thanks
-Glenn

**Comment by adamnovak** [comment]
The samples are downloaded, but the alignments need to be run still. I'll close this and make another issue.
