### ISSUE TITLE
Quantify VG slowdown if any on BRCA vs. old time stats

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#262]

**Comment by adamnovak** [comment]
For the runs that have completed, the vg runtimes are in line with what I have seen previously:

```
- NA06894 on Azure: 1.7194550037384033 seconds / 10024 reads = 171.533819 microseconds
        - HG00732 on Kolossus: 7.456632852554321 seconds / 44236 reads = 168.564808 microseconds

        - OK so in this case it's actually faster.

        - NA12275 on Azure on k31 BRCA1: 6.612050771713257 seconds / 4600 reads = 1.43740234 milliseconds
        - HG00732 on Kolossus: 43.946983098983765 seconds / 44236 reads = 993.466478 microseconds

        - Some graphs are way slower than others, but VG does not seem to have a terrible performance regression, at least in the BRCA1 graphs that have finished.
```

However, on the runs that are still running (like HG00732 to debruijn-k31 sma), vg is way over the predicted runtime for that graph and read count.

Trying to align another sample to that particular graph, I've managed to get VG to hang on the read `GTTTGTGGAAGACTCATCTTGTGAAAAGCATTTTATGAGTGCCCACGTTGGCTAAATTTAAAAGTCAACTATATAT`.

That obviously means it won't work for the evaluation, so I'm going to debug it.

**Comment by glennhickey** [comment]
I haven't counted, but it did seem to me that -e 5 with the new logic can
generate more kmers for some graphs than -e 7 with the old logic.  If this
is true, it could explain why some graphs seem slower.  It also suggests
that tuning down the indexing parameters could be worth considering in
order to get these all run this month....

**Comment by adamnovak** [comment]
This is post-indexing.

The problem is that with the new path ranks, a path can visit a node thousands of times, and some do. And loading the paths into the graph from the rocksdb index is n^2 due to how they are indexed in the vg object. xg has a flag to disable loading paths during the mapping step; this is needed for the rocksdb index as well.

**Comment by glennhickey** [comment]
I was thinking index size could impact alignment time...

Anyway, that's good news if it's just a matter of skipping rocksdb paths,
as that sounds like a quick fix.

**Comment by adamnovak** [comment]
OK I have fixed this. I'll address the other vg bug and make a new official release (and run the high coverage alignments).

**Comment by glennhickey** [comment]
Hi Adam,

I just noticed that I have a vg call job taking forever on this graph

/cluster/home/hickey/ga4gh/hgvm-graph-bakeoff-evalutations/high_coverage_graphs/
debruijn-lrc_kir-k63.vg

Seems like it's getting stuck at the loading phase.  Given that debruijn's
famous for giant paths, I suspect this is related to what you were saying
in this thread about ranks blowing up the loading time.  Have you run into
this issue on .vg files in addition to the rocksdb indexes?

thanks
-Glenn

**Comment by adamnovak** [comment]
Hello,

Try this:

https://github.com/adamnovak/vg/releases/tag/graph-bakeoff-0.3

I've completely thrown out the n^2 part of path loading.

-Adam

**Comment by glennhickey** [comment]
Works like a charm.  Thanks!
