### ISSUE TITLE
Make allele graph figures to explain David's graph comparison for the bake-off

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#28]

**Comment by benedictpaten** [comment]
I think we should also include some example evaluations using this
framework at the end of the document - as we discussed yesterday, e.g.
comparison of a large read set (represented as an alleleSet) to a pair of
side graphs, or similar comparison with exon/gene sets. We should also
discuss the case that the alleles are all one base long - in which case you
have something analogous to what we did with maf comparison.

**Comment by macieksmuga** [comment]
@benedictpaten does David's more worked-out example cover your request? As far as I understand, one-base-long alleles are now disallowed, as David ruled out alleles with "loose" ends - they either end on actual bases, or are pure join alleles.

**Comment by adamnovak** [comment]
Isn't a one-base allele with no dangling joins still a valid allele? It's
just a fairly trivial one.

On Wed, May 13, 2015 at 4:35 PM, Maciek Smuga-Otto <notifications@github.com

**Comment by macieksmuga** [comment]
@adamnovak you're right, of course. However without the danglies, it's not possible to embed it in any context, except through a very liberal sprinkling of join alleles (which would bear the brunt of defining all joins in the graph, implicit or explicit) throughout. Perhaps that's the example @benedictpaten was referring to?
