### ISSUE TITLE
Agree on colors

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#282]

**Comment by adamnovak** [comment]
How about #a6cee3
#1f78b4
#b2df8a
#33a02c
#fb9a99
#e31a1c
#fdbf6f
#ff7f00
#cab2d6
#6a3d9a
#ffff99
#b15928

from http://colorbrewer2.org/

And then add black?

**Comment by adamnovak** [comment]
#a6cee3: Curoverse
#1f78b4: Cactus
#b2df8a: Simons
#33a02c: Camel
#fb9a99: SNP 1kg
#e31a1c: De Bruijn K31
#fdbf6f: Phased 1kg
#ff7f00: De Bruijn K63
#cab2d6: vglr
#6a3d9a: PRG
#ffff99: trivial
#b15928: SBG
#000000: refonly

Order alphabetically by legend names

**Comment by adamnovak** [comment]
Also, names:
No underscore in LRC KIR region name

Cactus
Camel
SGDP (aka simons)
PRG
1KG
1KG Haplo
Curoverse
VGLR
7BG
De Bruijn 31
De Bruijn 63
Trivial
Reference

**Comment by adamnovak** [comment]
I think we might want to change the yellow for trivial to something darker, but other than that these are fine.

**Comment by srblum** [comment]
Trivial color: #b1b300
