### ISSUE TITLE
Download and run the platinum pedigree samples

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#295]

**Comment by adamnovak** [comment]
Maybe just NA17878 trio (NA12877, NA12878, NA12879)

**Comment by adamnovak** [comment]
The full pedigree is here: http://blog-test.goldenhelix.com/wp-content/uploads/2013/03/Utah-Pedigree-1463-with-NA12878.png

Ignore the green circle.

That trio is indeed a trio, and it's what I'm downloading, but there are also way more children, and also some parents for both the parents here.

**Comment by adamnovak** [comment]
I have downloaded those three samples to `/cluster/home/anovak/hive/ga4gh/bake-off/hgvm-graph-bakeoff-evalutations/platinum_reads` and am running the alignments now.

**Comment by adamnovak** [comment]
OK, these are now aligned, in `/cluster/home/anovak/hive/ga4gh/bake-off/hgvm-graph-bakeoff-evalutations/platinum_alignments`

**Comment by glennhickey** [comment]
thanks!
