### ISSUE TITLE
Talk to Justin Zook and Beau about getting our VCFs compared

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#322]
Beau might know how to do it.

We could also try  Peter Krusche or Kevin Jacobs's tools; we should e-mail them too.

**Comment by fnothaft** [comment]
Here's @beaunorgeot's comparison scripts: https://github.com/BD2KGenomics/gatk-whole-genome-pipeline/blob/master/GenotypeConcordance.sh

**Comment by adamnovak** [comment]
I've sent out e-mails to everybody but Beau (since I already have his script).

I think we're going to need some VCFs of the truth set converted into local "ref" coordinates for our regions.

**Comment by adamnovak** [comment]
OK I have a script that _should_ be able to run through and compare with the GATK.

At first glance, we occasionally agree with the Platinum calls, but generally we're making up spurious deletions or disagreeing about what alleles are options at a site.

**Comment by adamnovak** [comment]
We have a whole normalize-and-GATK pipeline going for the paper that I think we're going to stick with, unfortunately.
