### ISSUE TITLE
Preserve alts coordinates in glenn2vcf

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/hgvm#353]
It would be really nice to have the input coordinates preserved somewhere in the ouput of glenn2vcf (snp id field (3rd col) would be a decent place). ex:

input: 10 71 G  A,-
old output: chr13  971   .  G  A  0  .  .  GT 1/1
new output: chr13  971   10.71  G  A  0  .  .  GT 1/1

I wasn't able to figure out how to do this after a quick look at the code, but perhaps it's a trivial addition for you Adam (if not, then not worth it as it's easy enough to go back and forth for refonly which is what I'm debugging on now)

**Comment by adamnovak** [comment]
OK I've done this, at least for novel SNPs (in node.offset format) and variants representing the replacement of reference material with a node (in just node number format). I didn't do anything for deletions; those still have `.` for an ID.

**Comment by glennhickey** [comment]
Sounds perfect, thanks so much.
