### ISSUE TITLE
Fill in graph positions on GVCF/<NON_REF> variants in glenn2vcf

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#356]

**Comment by glennhickey** [comment]
Hi Adam,

I'm looking at false positives now.  Would it be possible to add the
coordinates for SNPs that are ref calls on snp1kg?  Right now I get a
number, but I don't know what to make of it ex:

. 32351798 3123 T A 0 . . GT 1/0

Is it a node id?

**Comment by adamnovak** [comment]
Yes, that's a node ID. It gives just a node ID and no offset only when it's
asserting the existence of an alt allele node.

The allele is always the whole sequence of the node, so in this case it
looks like that node is a single-base SNP.

I could add a node offset to these, but it would always be 0 (because the
variant always includes the whole node).

-Adam

**Comment by glennhickey** [comment]
OK thanks. That's fine the way it is.
