### ISSUE TITLE
Look at aligned read score distributions for platinum genomes and pick a score cut-off

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#364]

**Comment by adamnovak** [comment]
I want to pick a score cut-off that throws out the bad mappings while leaving the good ones. But it's hard to see in a histogram which is which...

Maybe I can find a threshold to separate primary from secondary?

**Comment by glennhickey** [comment]
That sounds fine to me.  I will implement a max score difference (primary
vs secondary) threshold to go with the absolute score thresholds in there
already. We may also want to consider a cap on the number of secondary
alignments we allow as well.

**Comment by adamnovak** [comment]
As in total in a sample? Because VG is only producing up to one secondary alignment per read.

**Comment by adamnovak** [comment]
I made some plots and there isn't a good cut-off point that I can see. I think Glenn is going to try some ranges.

**Comment by glennhickey** [comment]
Oops, thought there could be multiple secondaries for some reason. never
mind.
