### ISSUE TITLE
Look into not throwing out all the snps from the haplo graphs

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#367]
We throw out anything that doesn't attach to the primary path at both ends, which for the haplo graphs is most of everything.

**Comment by adamnovak** [comment]
OK, I've updated glenn2vcf with a --bubbles/-b option, which, when it finds a node not anchored at both ends, tries to find some arbitrary path back to the primary path of 10 nodes or fewer in each direction, and asserts that that path exists.

It possibly ought to be more careful and attempt to pathfind only through nodes that have been called as present, but this was the easiest thing to get working today.

**Comment by adamnovak** [comment]
@glennhickey I've pushed up another version that only builds bubbles from nodes that are called as present. I don't know how consistently the haplo1kg graphs are having their bubbles called (as a single missing base or node will kill a whole bubble), but you can update to the new version and see if that fixes the haplo1kg precision.

**Comment by adamnovak** [comment]
OK, I've decided not to require that the actual anchoring nodes be present, because they could have holes in them if they have homozygous alt SNPs.

**Comment by glennhickey** [comment]
Just seeing the last few messages in this thread now, for some reason.
Will rerun with latest --bubbles version.
