### ISSUE TITLE
Try hap.py and/or vcf-eval

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#368]

**Comment by adamnovak** [comment]
hap.py can do normalization itself apparently

**Comment by glennhickey** [comment]
I'm plugging in hap.py now, and will see what roc plot output looks like.   It seems to run on glenn2vcf output and give sensible results so far.

**Comment by glennhickey** [comment]
One idea to make hap.py run through is to set 0|1 genotypes for everything.

**Comment by glennhickey** [comment]
Adam's recent change to glenn2vcf looks like it improves genotypes markedly.  Definitely worth looking into these tools again.   Won't help with current issues we see in the sompy comparisons, but should strengthen existing results. 

Also:  should try to see if anything from PrecisionFDA can be used (difficulty: they're on grc37)

**Comment by glennhickey** [comment]
hap.py and vcf eval are now running.  Results aren't too bad in general.   But getting the som.py results shaped up remains priorty for bakeoff
