### ISSUE TITLE
Convince Erik that he wants us to build a haplotype-aware aligner on top of/into VG

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#376]
I don't want this to be another random bioinformatics software that nobody can have/will use, but also we can't just be adding in every research project into VG if it's going to be a serious toolchain, if only because of the number of command-line options it would need.

**Comment by benedictpaten** [comment]
We should sketch out the algorithm first before going to Erik. I think
Richard will be v. interested.

**Comment by adamnovak** [comment]
So I talked to Erik about this in Japan, and he thinks that we'd really gain more benefit from throwing kmers out of the GCSA index if they're inconsistent with the stored haplotypes. It seems like that would probably work without making GCSA explode, but I'm not convinced it's really better than accounting for haplotypes at the local alignment stage.
