### ISSUE TITLE
Look at some varaints that Glenn finds that we're missing in SMA and work out why we miss them

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#380]
Or just complain that they're obvious with nice depth and everything and that we should have called them

**Comment by glennhickey** [comment]
Hi Adam,

If you pull evalutations, scripts/vcfCompare.py and scripts/vcfDelta.py
have been updated to be consistent with som.py (used for my roc plots).
They are probably easier to work with.

For the roc plots, I put links to the data sets for the rightmost (highgest
recall) points in my latest slides here

/cluster/home/hickey/ga4gh/hgvm-graph-bakeoff-evalutations/missing_recall

The leftmost points (highest precision) are here

/cluster/home/hickey/ga4gh/hgvm-graph-bakeoff-evalutations/missing_precision

The missing_recall folder contains sets of the false_negatives were talking
about for lrc_kir and sma (slides 93 and 94).  Same goes for false
positives in missing_precision.  Both directories have a README showing the
command lines used to create these sets.

All the calling output is in "platinum_variants" and comparison results are
in "platinum_comparison" subdirs.  For example the glenn2vcf for sma-snp1kg
input (txt) and output (vcf) would be

platinum_variants/sma/snp1kg/NA12878_sample.txt
platinum_variants/sma/snp1kg/NA12878_sample.vcf

Let me know if there's anything else you need!

thanks
-Glenn
