### ISSUE TITLE
Make sure the 1kg blacklist was applied when making the graph, and that we aren't using the blacklister regions for precision or recall

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#396]

**Comment by adamnovak** [comment]
@glennhickey Can you do this? You make the 1kg graphs (right?) and you have taken over the comparison scripts.

**Comment by glennhickey** [comment]
Which blacklist do you mean, exactly?

**Comment by adamnovak** [comment]
I don't really know; David wanted me to make sure I was using "the
blacklist", from 1000 Genomes.

I think it's a list of regions where the 1000 Genomes people felt there was
too much weirdness, variability, and/or misassembly and where they thus
declined to make calls. I _think_ our 1000 Genomes VCFs would already
respect it, but it's possible we could be calling novel, spurious SNPs in
these regions, and that they could be overlapping with the high confidence
regions from Platinum Genomes.

-Adam

**Comment by glennhickey** [comment]
I see.  Poking around, I think this is what we're talking about

ftp://ftp.1000genomes.ebi.ac.uk/vol1/ftp/release/20130502/supporting/accessible_genome_masks/

Of course, there's no HG38 versions.  It seems reasonable to cut these
areas out of the comparison, though unlikely that they significantly
overlap the Platinum Genomes confident regions.  I'll see what happens
using a lifted over version.

**Comment by glennhickey** [comment]
Results of limiting comparison to the 1000 Genomes "strict" region are trickling into the "1000 genomes strict region" subdir of Variants Plots.  Everyone does much better, though the same patterns hold (only looked at LRC_KIR and SMA) so far.

**Comment by glennhickey** [comment]
Using / not using 1kg black list now option in pipeline.  Keeping it off for now as it doesn't make a big difference in the relative performances
