### ISSUE TITLE
Make a slide showing the BWA-VG mismatches that we fixed

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#434]
For April 13 call

**Comment by adamnovak** [comment]
Also include things we are fixing in the paper: why simons looks bad, etc.

**Comment by adamnovak** [comment]
Show off how vg is a community project

**Comment by glennhickey** [comment]
Hi Adam,

Here's a session with the three versions

http://genome.ucsc.edu/cgi-bin/hgTracks?hgS_doOtherUser=submit&hgS_otherUserName=hickey&hgS_otherUserSessionName=lrc_kir_fn_5

Replace fn_5 with fn_1..10 / fp_1..5 for other examples (but they won't
have all tracks).  The tracks are

OLD VG

track type=bam name="LRC_KIR ORIGINAL SURJECT BAM" description="LRC_KIR
ORIGINAL SURJECT BAM" pairEndsByName=. pairSearchRange=10000
chromosomes=chr19 bamColorMode=gray maxWindowToDraw=200000 db=hg38
visibility=pack bigDataUrl=
http://hgwdev.cse.ucsc.edu/~ewingad/gtemp/lrc_kir_cases_march_29/vg_orig/NA12878_surject.bam

NEW VG

track type=bam name="LRC_KIR SURJECT BAM" description="LRC_KIR SURJECT BAM"
pairEndsByName=. pairSearchRange=10000 chromosomes=chr19 bamColorMode=gray
maxWindowToDraw=200000 db=hg38 visibility=pack bigDataUrl=
http://hgwdev.cse.ucsc.edu/~ewingad/gtemp/lrc_kir_cases_march_29/NA12878_surject.bam

BWA MEM

track type=bam name="LRC_KIR BWA MEM BAM" description="LRC_KIR BWA MEM BAM"
pairEndsByName=. pairSearchRange=10000 chromosomes=chr19 bamColorMode=gray
maxWindowToDraw=200000 db=hg38 visibility=pack bigDataUrl=
http://hgwdev.cse.ucsc.edu/~ewingad/gtemp/lrc_kir_cases_march_29/NA12878.bam

**Comment by adamnovak** [comment]
Thanks for these. I think we probably only need one example in the slides, right?
