### ISSUE TITLE
Fix vg call likelihoods

### ISSUE THREAD

**Issue by glennhickey** [BD2KGenomics/hgvm#463]
We need good qualities in the VCF, which means being smarter about likelihoods.  Old way of just using samtools diploid model doesn't carry over properly to variation already in graph.   Need to split into monoploid values for each position, then recombine in glenn2vcf, or something else that will be consistently applied for both "reference" and "non-reference" variants.

**Comment by adamnovak** [comment]
The vg call likelihoods might still be bad, but they no longer suffer from the problems of the model we were using when this issue was opened.
