### ISSUE TITLE
Get xg fix merged into vg and get command line for running the genotyper to Glenn

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#465]
It might not work at all on things bigger than BRCA2, but Glenn wants to run it through his pipeline as is.

**Comment by adamnovak** [comment]
@glennhickey I have been using `vg genotype` like this:

`vg genotype platinum_graphs_extracted/snp1kg-brca2.vg reads.index -pv -q -i -C -c 13 -o 32314860 | tee test.vcf`

The options are:
-p: print progress info
-v: output VCF
-q: use mapping qualities
-i: do realignment for indel sites
-C: use Cactus to find sites
-c: use this contig name
-o: use this offset for positions

There's still an issue with me spitting out a hardcoded "255" for the quality of ref-allele-only sites, but once https://github.com/vgteam/vg/pull/424 is in you should have the same genotyper I have, where the false positives I have been finding look like real calls, and the false negatives I have been finding look either unsupported or like they are being lost to ambiguous indel contexts.

I haven't tested it on the revised alignments yet, but it should be better than it was.

**Comment by glennhickey** [comment]
Great, thanks!  I'll give it a run once #424's in (and most of the
alignments are done)
