### ISSUE TITLE
Plan CI System at 7/17/17 meeting

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#468]
At the planning meeting, Benedict wants to plan an amazing CI system that will run whole chromosomes on AWS via Toil from Jenkins, make ROC curves like Erik has, and produce nice reports we can browse. Glenn and I will write it.

**Comment by glennhickey** [comment]
Good idea.  I think step one will be getting Erik's latest simulation into
toil-vg.  I'll take a look at his current scripts in the mapper branch
tomorrow.

**Comment by adamnovak** [comment]
We should have a look at these other people who use Jenkins to run their analyses: http://biouno.org/2016/03/07/Creating-a-Jenkins-Data-Science-Platform
