### ISSUE TITLE
Run the high coverage bakeoff analysis

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#477]
Should use Erik's new mapper he is trying to merge today.

**Comment by glennhickey** [comment]
Spot checking  a small run on NA12878.  Biggest change, again, is primary getting better.    Overall indel F1 now:

snp1kg	0.760398199918
refonly	0.754319180088
freebayes	0.753863839571
platypus	0.795347686216

Last time I checked:

snp1kg	0.754597858908
refonly	0.731550489552

but the PR curves still look decent for indels.   When including SNPs in addition to indels, primary now slightly better 

snp1kg	0.869504475005
refonly	0.872305741713

Last time I checked

snp1kg	0.870738093137
refonly	0.860059208092

running the other sample now.
