### ISSUE TITLE
Rewrite references/search endpoint for reference server

### ISSUE THREAD

**Issue by adamnovak** [BD2KGenomics/hgvm#6]

**Comment by benedictpaten** [comment]
Issues should only be in the backlog when they are blocked or low priority

**Comment by hannes-ucsc** [comment]
Take a look at cgcloud-jenkins

**Comment by macieksmuga** [comment]
Hannes, could you instruct us in successful waffling? I feel like we're drowning in a sea of little boxes already, and we barely even started with it!

**Comment by hannes-ucsc** [comment]
Use milestones to filter out issues from previous milestones. That's what
the Pipelines team will be doing.

On Thu, Apr 30, 2015 at 3:30 PM, Maciek Smuga-Otto <notifications@github.com

> wrote:
> 
> Hannes, could you instruct us in successful waffling? I feel like we're
> drowning in a sea of little boxes already, and we barely even started with
> it!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/BD2KGenomics/hgvm/issues/6#issuecomment-97989942.

## 

Hannes Schmidt
Software Engineer
Center for Biomolecular Science and Engineering
University of California, Santa Cruz

(206) 696-2316 (cell)
hannes@ucsc.edu

**Comment by macieksmuga** [comment]
@hannes-ucsc Makes sense, and it would force us to start setting up milestones :)

**Comment by benedictpaten** [comment]
Let's try to do this in the meeting today.

On Thu, Apr 30, 2015 at 5:10 PM, Maciek Smuga-Otto <notifications@github.com
